---
# Should be perfomed in the account with DNS Zone
- name: Create the VPC authorization association.
  shell: "aws-vault exec play -- aws route53 create-vpc-association-authorization --hosted-zone-id {{ associate_zone_id }} --vpc VPCRegion={{ associate_vpc_region }},VPCId={{ associate_vpc_id }}"

# Should be performed in the account with the VPC
- name: Associate the VPC to the zone.
  shell: "aws-vault exec maishsk -- aws route53 associate-vpc-with-hosted-zone --hosted-zone-id {{ associate_zone_id }} --vpc VPCRegion={{ associate_vpc_region }},VPCId={{ associate_vpc_id }}"

# Should be perfomed in the account with DNS Zone
- name: Delete the VPC authorization association.
  shell: "aws-vault exec play -- aws route53 delete-vpc-association-authorization --hosted-zone-id {{ associate_zone_id }} --vpc VPCRegion={{ associate_vpc_region }},VPCId={{ associate_vpc_id }}"
