---
- name: Disassociate a VPC from a DNS zone.
  shell: "aws route53 disassociate-vpc-from-hosted-zone --hosted-zone-id {{ associate_zone_id }} --vpc VPCRegion={{ associate_vpc_region }},VPCId={{ associate_vpc_id }}"
